name: Build and Check

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: sudo apt-get install cppcheck pandoc
    - name: Build
      run: make
    - name: Check
      run: make check
    - name: Build docs
      run: make man
    - name: Release build
      run: make man
      env:
        RELEASE_BUILD: 1
