name: C/C++ CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: sudo apt-get install cppcheck pandoc
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make man
      run: make man
